# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DisentangleLaunch < Formula
  desc "Deployment orchestrator for the Disentangle Network"
  homepage "https://github.com/disentangle-network/launch"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disentangle-network/launch/releases/download/v0.3.0/launch_0.3.0_darwin_amd64.tar.gz"
      sha256 "006fcc1806a1173908581d6782ff8ca9fd2b5f85b89c225073d6320488f57b6e"

      def install
        bin.install "launch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disentangle-network/launch/releases/download/v0.3.0/launch_0.3.0_darwin_arm64.tar.gz"
      sha256 "a9a752cf667d20161392f0d83b54a5d2885973ee290c5ac4b3629c7d5d03fe31"

      def install
        bin.install "launch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.3.0/launch_0.3.0_linux_amd64.tar.gz"
      sha256 "7af8e3e1d0d14965d23cb21eade606774468e4410edab994f4d25e95cd472ac2"
      def install
        bin.install "launch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.3.0/launch_0.3.0_linux_arm64.tar.gz"
      sha256 "53c11a3f0fe673ff791a918c334d374aaa4e017014b07d5457b152eb4fa6b439"
      def install
        bin.install "launch"
      end
    end
  end

  test do
    system "#{bin}/launch", "--version"
  end
end
