# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DisentangleLaunch < Formula
  desc "Deployment orchestrator for the Disentangle Network"
  homepage "https://github.com/disentangle-network/launch"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disentangle-network/launch/releases/download/v0.4.3/launch_0.4.3_darwin_amd64.tar.gz"
      sha256 "6f0565f0ea13d4fa34f83a7794d49ee5b40db05709b692271aaac25732385b61"

      def install
        bin.install "launch-disentangle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disentangle-network/launch/releases/download/v0.4.3/launch_0.4.3_darwin_arm64.tar.gz"
      sha256 "8d8f357f8e73a4fe3693c67cc052cd593e57ef03f425be909a2d9f8b7e75ca70"

      def install
        bin.install "launch-disentangle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.4.3/launch_0.4.3_linux_amd64.tar.gz"
      sha256 "86dc899162a96aed247bafc2f6735a43842ba3dc65dd9cf4569a2955bf9c6655"
      def install
        bin.install "launch-disentangle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.4.3/launch_0.4.3_linux_arm64.tar.gz"
      sha256 "a83a0b13e068e916184250ae3e2b516d4cc96399cfb812a25ad5fe71b4b53dd8"
      def install
        bin.install "launch-disentangle"
      end
    end
  end

  test do
    system "#{bin}/launch-disentangle", "--version"
  end
end
