# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Launch < Formula
  desc "Deployment orchestrator for the Disentangle Network"
  homepage "https://github.com/disentangle-network/launch"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disentangle-network/launch/releases/download/v0.2.0/launch_0.2.0_darwin_amd64.tar.gz"
      sha256 "93d3331169f5a98b46735e84c6762174c8e141caf7f4d8a8c07052eb1a878c7e"

      def install
        bin.install "launch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disentangle-network/launch/releases/download/v0.2.0/launch_0.2.0_darwin_arm64.tar.gz"
      sha256 "34a3aeca345476baea73d98b406522af65a6cfb2aa0833c691af7b394dcf5f89"

      def install
        bin.install "launch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.2.0/launch_0.2.0_linux_amd64.tar.gz"
      sha256 "78deb16e274278bccf292d4e263064ca8ad2a69bf19eded8dd1ad68532cee00b"
      def install
        bin.install "launch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disentangle-network/launch/releases/download/v0.2.0/launch_0.2.0_linux_arm64.tar.gz"
      sha256 "faad4a6bce4bddaff7213f0c96f6215ad249d4f85327e71414fa76a69044f1a0"
      def install
        bin.install "launch"
      end
    end
  end

  test do
    system "#{bin}/launch", "--version"
  end
end
