# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OciTfBootstrap < Formula
  desc "Generate ready-to-use Terraform from OCI tenancy discovery"
  homepage "https://github.com/larsenclose/oci-tf-bootstrap"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/larsenclose/oci-tf-bootstrap/releases/download/v0.1.0/oci-tf-bootstrap_0.1.0_darwin_amd64.tar.gz"
      sha256 "11dcf383d7cc7c02dd44b49e6302bf485ea755c676b901b50781edcee1584697"

      def install
        bin.install "oci-tf-bootstrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/larsenclose/oci-tf-bootstrap/releases/download/v0.1.0/oci-tf-bootstrap_0.1.0_darwin_arm64.tar.gz"
      sha256 "f2dcd0f063df8eaf4f6c6e29e7611ebead04a1d39ea2bc3ebae91cdd17775fe2"

      def install
        bin.install "oci-tf-bootstrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/larsenclose/oci-tf-bootstrap/releases/download/v0.1.0/oci-tf-bootstrap_0.1.0_linux_amd64.tar.gz"
      sha256 "e1678a42765fb92a4e45b19074a4be359144fc3b05b012c5eb34f3f35898e186"
      def install
        bin.install "oci-tf-bootstrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/larsenclose/oci-tf-bootstrap/releases/download/v0.1.0/oci-tf-bootstrap_0.1.0_linux_arm64.tar.gz"
      sha256 "c4b3f9503c030d06ee53578089f8a8d5de7f4a78e39102ebea91feb81bce3f74"
      def install
        bin.install "oci-tf-bootstrap"
      end
    end
  end

  test do
    system "#{bin}/oci-tf-bootstrap", "--help"
  end
end
